# Generated by Django 4.1.6 on 2023-03-02 18:09

import autoslug.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='img/', verbose_name='Изображение')),
                ('rating', models.IntegerField(blank=True, default=0, verbose_name='Рейтинг')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('username', models.CharField(max_length=32, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='О чем вы хотите рассказать?')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('start_time', models.DateTimeField(verbose_name='Дата старта')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность соревнования')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('actual', models.BooleanField(default=True, verbose_name='Не закончен')),
                ('verified', models.BooleanField(default=False, verbose_name='Проверено администратором')),
                ('rating', models.BooleanField(default=False, verbose_name='Рейтинговое ли соревнование')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название задания')),
                ('condition', models.TextField(verbose_name='Описание задания')),
                ('required_input', models.TextField(verbose_name='Входные данные')),
                ('required_output', models.TextField(verbose_name='Выходные данные')),
                ('input_exmaple', models.TextField(verbose_name='Пример ввода кода')),
                ('output_exmaple', models.TextField(verbose_name='Пример ввода кода')),
                ('extra_text', models.TextField(blank=True, verbose_name='Дополнительные пояснение, недочеты')),
                ('input_values_1', models.TextField(verbose_name='Вводимые значения 1')),
                ('output_values_1', models.TextField(verbose_name='Получаемые значения 1')),
                ('input_values_2', models.TextField(verbose_name='Вводимые значения 2')),
                ('output_values_2', models.TextField(verbose_name='Получаемые значения 2')),
                ('input_values_3', models.TextField(verbose_name='Вводимые значения 3')),
                ('output_values_3', models.TextField(verbose_name='Получаемые значения 3')),
                ('input_values_4', models.TextField(verbose_name='Вводимые значения 4')),
                ('output_values_4', models.TextField(verbose_name='Получаемые значения 4')),
                ('input_values_5', models.TextField(verbose_name='Вводимые значения 5')),
                ('output_values_5', models.TextField(verbose_name='Получаемые значения 5')),
                ('score', models.PositiveIntegerField(help_text='Указывать половину от максимального числа', verbose_name='Количество очков за задание')),
                ('compet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competition')),
            ],
        ),
        migrations.CreateModel(
            name='ScorePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('link_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('files', models.FileField(null=True, upload_to='article_files/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.article')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Количество полученых очков')),
                ('successfully', models.BooleanField(default=False, verbose_name='Успешное решение')),
                ('error', models.CharField(default='-', max_length=30, verbose_name='Ошибка')),
                ('document', models.FileField(upload_to='comp_files/')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрытая попытка')),
                ('link_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competition')),
                ('link_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
                ('link_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
